/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.quiz1;

import javax.swing.JOptionPane;
/**
 *
 * @author ASUS
 */
public class Pesanan extends javax.swing.JFrame {

    
    public Pesanan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        eMenu = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        ePesanan = new javax.swing.JTextField();
        eHarga = new javax.swing.JTextField();
        eJumlah = new javax.swing.JTextField();
        eTotal = new javax.swing.JTextField();
        eBayar = new javax.swing.JTextField();
        eKembalian = new javax.swing.JTextField();
        btnSimpan = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        btnTotal = new javax.swing.JButton();
        btnHapus = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 235, 235));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(255, 204, 204));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 45)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(165, 99, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("GOOD CAFE ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, -1, 40));

        jLabel3.setText("Menu");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        eMenu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilihan Minuman", "Americano", "Choco Cookies", "Chocolate", "Cappucino", "Matcha" }));
        eMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eMenuActionPerformed(evt);
            }
        });
        getContentPane().add(eMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 130, 30));

        jLabel4.setText("Pesanan");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        jLabel5.setText("Harga");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, -1));

        jLabel6.setText("Jumlah Pesanan");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, -1, -1));

        jLabel7.setText("Total");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, -1, -1));

        jLabel8.setText("Bayar");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, -1, -1));

        jLabel9.setText("Kembalian");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 540, -1, -1));
        getContentPane().add(ePesanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 130, 30));
        getContentPane().add(eHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, 130, 30));
        getContentPane().add(eJumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, 130, 30));
        getContentPane().add(eTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 450, 130, 30));
        getContentPane().add(eBayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 490, 130, 30));
        getContentPane().add(eKembalian, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 530, 130, 30));

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        getContentPane().add(btnSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 670, -1, -1));

        jButton2.setText("Hapus");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 670, -1, -1));

        btnKeluar.setText("Keluar");
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });
        getContentPane().add(btnKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 670, -1, -1));

        jLabel10.setText("=========================================================================================================================================================");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 400, 10));

        btnTotal.setText("Total");
        btnTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTotalActionPerformed(evt);
            }
        });
        getContentPane().add(btnTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 390, -1, -1));

        btnHapus.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Downloads\\ayo.png")); // NOI18N
        getContentPane().add(btnHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 713));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void eMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eMenuActionPerformed
        // TODO add your handling code here:
        switch (eMenu.getSelectedIndex()){
            case 1:
            {
                ePesanan.setText(String.valueOf("Americano"));
                eHarga.setText(String.valueOf("10000"));
            }
            break;
            case 2:
            {
                ePesanan.setText(String.valueOf("Choco Cookies"));
                eHarga.setText(String.valueOf("15000"));
                
            }
            break;
            case 3:
            {
                ePesanan.setText(String.valueOf("Chocolate"));
                eHarga.setText(String.valueOf("13000"));
            }
            break;
            case 4:
            {
                ePesanan.setText(String.valueOf("Cappucino"));
                eHarga.setText(String.valueOf("11000"));
            }
            break;
            case 5:
            {
                ePesanan.setText(String.valueOf("Matcha"));
                eHarga.setText(String.valueOf("10000"));
            }
            break;
            
        }
    }//GEN-LAST:event_eMenuActionPerformed

    private void btnTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTotalActionPerformed
        // TODO add your handling code here:
        double harga, jumlah, total;
            harga = Double.parseDouble(eHarga.getText());
            jumlah = Double.parseDouble(eJumlah.getText());
            total = harga * jumlah;
            eTotal.setText(String.valueOf(total));
    }//GEN-LAST:event_btnTotalActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        double harga, bayar, hasil;
            harga = Double.parseDouble(eHarga.getText());
            bayar = Double.parseDouble(eBayar.getText());
            hasil = bayar - harga;
            eKembalian.setText(String.valueOf(hasil));
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        eMenu.setSelectedIndex(0);
        ePesanan.setText(" ");
        eHarga.setText(" ");
        eJumlah.setText(" ");
        eTotal.setText(" ");
        eBayar.setText(" ");
        eKembalian.setText(" ");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "TERIMA KASIH TELAH BERBELANJA");
        System.exit(0);
    }//GEN-LAST:event_btnKeluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pesanan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnHapus;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnTotal;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField eBayar;
    private javax.swing.JTextField eHarga;
    private javax.swing.JTextField eJumlah;
    private javax.swing.JTextField eKembalian;
    private javax.swing.JComboBox<String> eMenu;
    private javax.swing.JTextField ePesanan;
    private javax.swing.JTextField eTotal;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
